<<<<<<< HEAD
export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
=======
export const ALL_PRODUCTS_REQUEST ="ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS ="ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL ="ALL_PRODUCTS_FAIL"

export const CLEAR_ERRORS ="CLEAR_ERRORS" 
>>>>>>> 4934fdf95e4744cfa83a7bd70011ae0878f4b5b3
