export const ALL_VENTAS_REQUEST = "ALL_VENTAS_REQUEST"
export const ALL_VENTAS_SUCCESS = "ALL_VENTAS_SUCCESS"
export const ALL_VENTAS_FAIL = "ALL_VENTAS_FAIL"

export const VENTA_DETAILS_REQUEST = "VENTA_DETAILS_REQUEST"
export const VENTA_DETAILS_SUCCESS = "VENTA_DETAILS_SUCCESS"
export const VENTA_DETAILS_FAIL = "VENTA_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"